# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Ermöglicht Speicherung von Daten in InfluxData TSDB z.B. zur Erzeugung von Graphen mit Grafana oder Chronograf (Plugin aus 2016)'
        en: ''
    maintainer: rthill
    tester: brandst
    keywords: database
    documentation: https://github.com/smarthomeNG/smarthome/wiki/Installation-Influx-Grafana        # url of documentation (wiki) page

    version: 1.0.0                 # Plugin version
    sh_minversion: 1.1             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: InfluxData          # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
